# TODO: Missing Licence Header

name: builds

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  client-smoke:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    name: Client Compiles on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout the app
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: compile client
      run: |
        cd client
        npm run setup
        npm run compile


  server-smoke:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    name: Server Compiles on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout the app
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: compile server
      run: |
        cd server
        npm run setup
        npm run compile